import React from "react";
import * as _Builtin from "./_Builtin";
import { Event } from "./Event";
import * as _utils from "./utils";
import _styles from "./Grid.module.css";

export function Grid({
  as: _Component = _Builtin.Block,
  categoryTitle = "Concerten",
  eventsGridSlot,
}) {
  return (
    <_Component className={_utils.cx(_styles, "event-type")} tag="div">
      <_Builtin.Block className={_utils.cx(_styles, "container")} tag="div">
        <_Builtin.Block
          className={_utils.cj(
            _utils.cx(_styles, "event-highlights"),
            "w-clearfix"
          )}
          id={_utils.cx(
            _styles,
            "w-node-c4dd5bd0-df61-d262-0682-b22c1646852a-16468528"
          )}
          tag="div"
        >
          <_Builtin.Block
            className={_utils.cx(_styles, "homepage-headings")}
            tag="div"
          >
            {categoryTitle}
          </_Builtin.Block>
          <_Builtin.Block
            className={_utils.cx(_styles, "div-block-89")}
            tag="div"
          >
            <_Builtin.Block
              className={_utils.cj(
                _utils.cx(
                  _styles,
                  "event-ticket-button-container",
                  "remove-absolute"
                ),
                "w-clearfix"
              )}
              tag="div"
            >
              <_Builtin.Block
                className={_utils.cx(_styles, "home-ticket-text")}
                tag="div"
              >
                {"See our concerten event agenda"}
              </_Builtin.Block>
            </_Builtin.Block>
          </_Builtin.Block>
          <_Builtin.Grid
            className={_utils.cx(_styles, "events-grid")}
            tag="div"
          >
            {eventsGridSlot ?? (
              <>
                <Event />
                <_Builtin.Block
                  className={_utils.cx(_styles, "event-block")}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(_styles, "event-grid-image")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646854c-16468528"
                    )}
                    width="auto"
                    height="auto"
                    loading="auto"
                    alt=""
                    src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080af21f74e4cd681b836_simple-minds.jpg"
                  />
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "h3",
                      "white-text-2",
                      "margin-left-20px",
                      "margin-bottom-0px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646854d-16468528"
                    )}
                    tag="div"
                  >
                    {"The Streamers"}
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cj(
                      _utils.cx(
                        _styles,
                        "event-stars-wrapper",
                        "margin-left-20px"
                      ),
                      "w-clearfix"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646854f-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "reviews-number-text",
                        "margin-top-0px"
                      )}
                      tag="div"
                    >
                      <_Builtin.Strong
                        className={_utils.cx(
                          _styles,
                          "similar-events-review-number"
                        )}
                      >
                        {"100+"}
                      </_Builtin.Strong>
                      {" reviews"}
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "event-button-grid-container",
                      "margin-top-5px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468559-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "event-ticket-button-container",
                        "remove-absolute"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cj(
                          _utils.cx(_styles, "button-content"),
                          "w-clearfix"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-icon")}
                          id={_utils.cx(
                            _styles,
                            "w-node-c4dd5bd0-df61-d262-0682-b22c1646855c-16468528"
                          )}
                          tag="div"
                        >
                          {""}
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-text")}
                          tag="div"
                        >
                          {"Koop Tickets"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "gradient")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468560-16468528"
                    )}
                    tag="div"
                  />
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(_styles, "event-block")}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(_styles, "event-grid-image")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468562-16468528"
                    )}
                    width="auto"
                    height="auto"
                    loading="auto"
                    alt=""
                    src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080af21f74e4cd681b826_kane.jpg"
                  />
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "h3",
                      "white-text-2",
                      "margin-left-20px",
                      "margin-bottom-0px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468563-16468528"
                    )}
                    tag="div"
                  >
                    {"The Streamers"}
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cj(
                      _utils.cx(
                        _styles,
                        "event-stars-wrapper",
                        "margin-left-20px"
                      ),
                      "w-clearfix"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468565-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "reviews-number-text",
                        "margin-top-0px"
                      )}
                      tag="div"
                    >
                      <_Builtin.Strong
                        className={_utils.cx(
                          _styles,
                          "similar-events-review-number"
                        )}
                      >
                        {"100+"}
                      </_Builtin.Strong>
                      {" reviews"}
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "event-button-grid-container",
                      "margin-top-5px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646856f-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "event-ticket-button-container",
                        "remove-absolute"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cj(
                          _utils.cx(_styles, "button-content"),
                          "w-clearfix"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-icon")}
                          id={_utils.cx(
                            _styles,
                            "w-node-c4dd5bd0-df61-d262-0682-b22c16468572-16468528"
                          )}
                          tag="div"
                        >
                          {""}
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-text")}
                          tag="div"
                        >
                          {"Koop Tickets"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "gradient")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468576-16468528"
                    )}
                    tag="div"
                  />
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(_styles, "event-block")}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(_styles, "event-grid-image")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468578-16468528"
                    )}
                    width="auto"
                    height="auto"
                    loading="auto"
                    alt=""
                    src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080af21f74e4cd681b82e_soldaat.jpg"
                  />
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "h3",
                      "white-text-2",
                      "margin-left-20px",
                      "margin-bottom-0px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468579-16468528"
                    )}
                    tag="div"
                  >
                    {"The Streamers"}
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cj(
                      _utils.cx(
                        _styles,
                        "event-stars-wrapper",
                        "margin-left-20px"
                      ),
                      "w-clearfix"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646857b-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "reviews-number-text",
                        "margin-top-0px"
                      )}
                      tag="div"
                    >
                      <_Builtin.Strong
                        className={_utils.cx(
                          _styles,
                          "similar-events-review-number"
                        )}
                      >
                        {"100+"}
                      </_Builtin.Strong>
                      {" reviews"}
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "event-button-grid-container",
                      "margin-top-5px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468585-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "event-ticket-button-container",
                        "remove-absolute"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cj(
                          _utils.cx(_styles, "button-content"),
                          "w-clearfix"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-icon")}
                          id={_utils.cx(
                            _styles,
                            "w-node-c4dd5bd0-df61-d262-0682-b22c16468588-16468528"
                          )}
                          tag="div"
                        >
                          {""}
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-text")}
                          tag="div"
                        >
                          {"Koop Tickets"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "gradient")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646858c-16468528"
                    )}
                    tag="div"
                  />
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(_styles, "event-block")}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(_styles, "event-grid-image")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646858e-16468528"
                    )}
                    width="auto"
                    height="auto"
                    loading="auto"
                    alt=""
                    src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080af21f74e4cd681b83e_14het.jpg"
                  />
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "h3",
                      "white-text-2",
                      "margin-left-20px",
                      "margin-bottom-0px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646858f-16468528"
                    )}
                    tag="div"
                  >
                    {"The Streamers"}
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cj(
                      _utils.cx(
                        _styles,
                        "event-stars-wrapper",
                        "margin-left-20px"
                      ),
                      "w-clearfix"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c16468591-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "reviews-number-text",
                        "margin-top-0px"
                      )}
                      tag="div"
                    >
                      <_Builtin.Strong
                        className={_utils.cx(
                          _styles,
                          "similar-events-review-number"
                        )}
                      >
                        {"100+"}
                      </_Builtin.Strong>
                      {" reviews"}
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "event-button-grid-container",
                      "margin-top-5px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c1646859b-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "event-ticket-button-container",
                        "remove-absolute"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cj(
                          _utils.cx(_styles, "button-content"),
                          "w-clearfix"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-icon")}
                          id={_utils.cx(
                            _styles,
                            "w-node-c4dd5bd0-df61-d262-0682-b22c1646859e-16468528"
                          )}
                          tag="div"
                        >
                          {""}
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-text")}
                          tag="div"
                        >
                          {"Koop Tickets"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "gradient")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c164685a2-16468528"
                    )}
                    tag="div"
                  />
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(_styles, "event-block")}
                  tag="div"
                >
                  <_Builtin.Image
                    className={_utils.cx(_styles, "event-grid-image")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c164685a4-16468528"
                    )}
                    width="auto"
                    height="auto"
                    loading="auto"
                    alt=""
                    src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b816_r5srllgr0v4fctnnpooq.jpg"
                  />
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "h3",
                      "white-text-2",
                      "margin-left-20px",
                      "margin-bottom-0px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c164685a5-16468528"
                    )}
                    tag="div"
                  >
                    {"The Streamers"}
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cj(
                      _utils.cx(
                        _styles,
                        "event-stars-wrapper",
                        "margin-left-20px"
                      ),
                      "w-clearfix"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c164685a7-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Image
                      className={_utils.cx(
                        _styles,
                        "small-star",
                        "next-small-star",
                        "margin-top-0px"
                      )}
                      width="auto"
                      height="auto"
                      loading="auto"
                      alt=""
                      src="https://uploads-ssl.webflow.com/65f080993bcf3b0164216f18/65f080ae21f74e4cd681b815_star-white.svg"
                    />
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "reviews-number-text",
                        "margin-top-0px"
                      )}
                      tag="div"
                    >
                      <_Builtin.Strong
                        className={_utils.cx(
                          _styles,
                          "similar-events-review-number"
                        )}
                      >
                        {"100+"}
                      </_Builtin.Strong>
                      {" reviews"}
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "event-button-grid-container",
                      "margin-top-5px"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c164685b1-16468528"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "event-ticket-button-container",
                        "remove-absolute"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cj(
                          _utils.cx(_styles, "button-content"),
                          "w-clearfix"
                        )}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-icon")}
                          id={_utils.cx(
                            _styles,
                            "w-node-c4dd5bd0-df61-d262-0682-b22c164685b4-16468528"
                          )}
                          tag="div"
                        >
                          {""}
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(_styles, "home-ticket-text")}
                          tag="div"
                        >
                          {"Koop Tickets"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(_styles, "gradient")}
                    id={_utils.cx(
                      _styles,
                      "w-node-c4dd5bd0-df61-d262-0682-b22c164685b8-16468528"
                    )}
                    tag="div"
                  />
                </_Builtin.Block>
              </>
            )}
          </_Builtin.Grid>
        </_Builtin.Block>
      </_Builtin.Block>
    </_Component>
  );
}
